/**
 * The building, as it is drawn inside an AR session.
 *
 * Requirements covered here:
 *   AR-2  the model is a single group whose matrix is set once from a hit-test
 *         pose, so it stays put while the user walks around it
 *   AR-3  completed zones render opaque, zones not yet executed render as a
 *         translucent ghost — the boundary comes from zone.status, never from
 *         a hard-coded floor number
 *   AR-4  colours come from ../riskBands, the same module the 2D Twin uses
 *
 * Deliberately schematic: boxes per zone, generated by the same zonesFor()
 * used by TWIN-1. No facade detail, no textures, no interiors — an AR session
 * on a tablet has a frame-rate budget (NFR-AR-1) and the information carried
 * here is status and risk, not architecture.
 */
import React, { useMemo } from 'react';
import * as THREE from 'three';
import { zonesFor, floorY, widthAt, zoneCenterX } from '../DigitalTwin.jsx';
import { RISK_COLORS } from './riskBands.js';

/** A zone counts as built when its work is done. Everything else is a ghost. */
export const isBuilt = (zone) => zone.status === 'הושלם';

export function zoneBoxes(spec) {
  return zonesFor(spec).map((zone) => {
    const w = widthAt(spec, zone.floor) / 2;
    const h = spec.floorHeight * 0.92;
    const d = spec.depth;
    return {
      zone,
      size: [w * 0.94, h, d],
      position: [zoneCenterX(spec, zone.floor, zone.zoneIndex), floorY(spec, zone.floor) + h / 2, 0],
      built: isBuilt(zone),
    };
  });
}

function ZoneBox({ box, selected, onSelect }) {
  const { zone, size, position, built } = box;
  const color = RISK_COLORS[zone.risk] ?? RISK_COLORS.unknown;
  return (
    <group position={position}>
      <mesh
        name={`zone:${zone.id}`}
        userData={{ zoneId: zone.id, zone }}
        onClick={(e) => {
          e.stopPropagation();
          onSelect(zone);
        }}
      >
        <boxGeometry args={size} />
        <meshStandardMaterial
          color={color}
          transparent={!built}
          opacity={built ? 1 : 0.28}
          roughness={0.85}
          metalness={0}
          depthWrite={built}
          side={built ? THREE.FrontSide : THREE.DoubleSide}
          emissive={selected ? color : '#000000'}
          emissiveIntensity={selected ? 0.55 : 0}
        />
      </mesh>

      {/* A wireframe edge keeps the ghost floors readable against a bright
          real-world background, where a 28%-opacity surface alone washes out. */}
      <lineSegments>
        <edgesGeometry args={[new THREE.BoxGeometry(...size)]} />
        <lineBasicMaterial color={built ? '#37474f' : color} transparent opacity={built ? 0.55 : 0.9} />
      </lineSegments>
    </group>
  );
}

/**
 * `anchorMatrix` is a THREE.Matrix4 captured from the hit test at placement
 * time (AR-2). Until it exists the model is not rendered at all — a building
 * floating at the origin of the tracking space is worse than no building.
 */
export default function ARModel({ spec, anchorMatrix, scale, selectedId, onSelect }) {
  const boxes = useMemo(() => zoneBoxes(spec), [spec]);
  if (!anchorMatrix) return null;
  return (
    <group matrixAutoUpdate={false} matrix={anchorMatrix}>
      <group scale={scale}>
        {boxes.map((b) => (
          <ZoneBox
            key={b.zone.id}
            box={b}
            selected={selectedId === b.zone.id}
            onSelect={onSelect}
          />
        ))}
      </group>
    </group>
  );
}
